stages:
  - code-quality
  - test

.ruby-setup:
  image: ruby:3.1.2-slim
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - $GEM_CACHE
  before_script:
    - bundle install

rubocop:
  stage: code-quality
  when: always
  extends:
    - .ruby-setup
  script:
    - bundle exec rubocop

slim-lint:
  stage: code-quality
  when: always
  extends:
    - .ruby-setup
  script:
    - bundle exec slim-lint app/views

test:
  stage: test
  when: on_success
  extends:
    - .ruby-setup
  script:
    - bundle exec rails test
