inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - db/schema.rb

Metrics/AbcSize:
  Max: 56
  Exclude:
    - db/**/*

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/BlockLength:
  Max: 35
  Exclude:
    - config/routes.rb
    - db/**/*

Metrics/MethodLength:
  Max: 35
  Exclude:
    - db/**/*

Layout/LineLength:
  Max: 200

Rails/SkipsModelValidations:
  Enabled: false
