default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('GENESIS_DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('GENESIS_DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('GENESIS_DATABASE_USERNAME', 'root') %>
  password: <%= ENV.fetch('GENESIS_DATABASE_PASSWORD', '1234') %>

development:
  <<: *default
  database: <%= ENV.fetch('GENESIS_DATABASE', 'genesis') %>_development

test:
  <<: *default
  database: <%= ENV.fetch('GENESIS_DATABASE', 'genesis') %>_test

production:
  <<: *default
  database: <%= ENV.fetch('GENESIS_DATABASE', 'genesis') %>
